Restructure navigation, add About item with Changelog
vshn/kb pull request #25
Opened 2020-04-10 21:15 UTC by bittner

These changes should align the navigation visually with the VSHN handbook.

- I noticed that it was difficult to move the Changelog to the bottom of the navigation in a clean fashion.
- I figured that the submenus would probably make sense to be present as modules in the files system.

The current solution seems clean from a maintenance point of view. It has a little downside, though:

- The "Knowledge Base" section is now located in a subpath "/knowledge-base/" (in the final URL)

Is there a way to avoid this? -- On the other hand, while it makes the URL longer, it would reflect the actual navigation structure (and content) in the URL path.

Let me know what you think. I'm happy to adapt the PR. My main concern was the location of the changelog menu item.

2020-04-16 07:35 UTC, akosma requested changes
Please do not use empty component names, as this is a non-documented and potentially non-supported feature.

2020-04-16 07:35 UTC, akosma commented on docs/antora.yml
> +name: ''
I see what you did there, and I'm split. Quoting Dan Allen (creator of Antora and Asciidoctor) in a Gitter message from Aug 20, 2019:
> the main issue is that there's no way to reference those pages from another module because the component name is empty. so there's still some work to do there.

This is a hack, pure and simple. I'm not very comfortable with this solution. I understand that you might not like the URLs generated by Antora, but this is a stretch IMHO.

2020-04-16 07:35 UTC, akosma commented on docs/antora.yml
> +name: ''
Reference of the quote: [link](https://gitter.im/antora/users?at=5d5b51080eff7d2dfee00a84)

2020-04-16 15:59 UTC, bittner commented on docs/antora.yml
> +name: ''
The alternative is to configure the `name` as the trailing part of the Nginx's document root path. I take a stab at that once I find the deployment configuration.

As I said, my main concern is to align the navigation structure (and mental model) of the KB with our Handbook. So, no worries.

2020-04-16 17:29 UTC, bittner commented on docs/antora.yml
> +name: ''
We can solve this problem by calling the module `ROOT`.

That would give the illusion that the new `ROOT` _folder_ is related to the default module name, which fixes the mental model broken by the hard-coded nature of the [ROOT module](https://docs.antora.org/antora/2.2/modules/#root-dir).

Unfortunately, the [`fs` output provider](https://docs.antora.org/antora/2.2/playbook/configure-output/#output-destinations) doesn't allow to relocate the additional static assets (`_` folder, `robots.txt`, `sitemap.xml` and `404.html`), which need to be moved into the `ROOT` folder. – Do you know a solution for that?

2020-04-16 17:35 UTC, bittner commented on docs/antora.yml
> +name: ''
On the other hand, this puristic view is probably exaggerated. Pragmatically speaking:

* Will we ever use the KB as a _module_?
* Will we ever build the KB together with, say, the Handbook and maintain cross-references to each other that Antora is meant to resolve?

The answer is most likely: No.

So we can probably live with that fact until Dan Allen has decided for a fix, or even forever.

Our customers will benefit. – What do you think?

2020-04-17 12:24 UTC, akosma commented on docs/antora.yml
> +name: ''
I do not think there's any benefit here. To be honest, I do not even see what is the problem we're trying to solve.

2020-05-05 11:46 UTC, closed without merging