WIP VSS public docs
vshn/kb pull request #28
Opened 2020-05-01 07:13 UTC by tobru

This brings the VSHN product documentation to the KB.

It's a WIP, do _not_ merge yet

2020-05-04 07:48 UTC, corvus-ch requested changes

2020-05-04 07:48 UTC, corvus-ch commented on docs/modules/PRODUCT/pages/index.adoc
> +Classiv VM managed services
`s/Classiv/Classic/`

2020-05-04 07:48 UTC, corvus-ch commented on docs/modules/PRODUCT/pages/vss_intro.adoc
> +TIP: This document is currently in public beta and being worked on actively
Maybe `WARNING` is more appropriate here.

2020-05-04 07:48 UTC, corvus-ch commented on docs/modules/PRODUCT/pages/vss_intro.adoc
> +NOTE: This includes the Kubernetes cluster and the Project Syn provided tooling, no customer application and services running on the cluster.
Maybe use ` IMPORTANT:`

2020-05-04 07:48 UTC, corvus-ch commented on docs/modules/PRODUCT/pages/vss_intro.adoc
> +* Continuous improvement of Alertrules based and day-to-day experience
`s/based and day-to-day/based on day-to-day/`

2020-05-04 07:48 UTC, corvus-ch commented on docs/modules/PRODUCT/pages/vss_price_model.adoc
> +TIP: This document is currently in public beta and being worked on actively
`WARNING` might be more appropriate here too.

2020-05-04 07:48 UTC, corvus-ch commented on docs/modules/PRODUCT/pages/vss_support_levels.adoc
> +TIP: This document is currently in public beta and being worked on actively
`WARNING` might be more appropriate here too.

2020-05-04 07:48 UTC, corvus-ch commented on docs/modules/PRODUCT/pages/vss_support_matrix.adoc
> +TIP: This document is currently in public beta and being worked on actively
`WARNING` might be more appropriate here too.

2020-05-04 07:48 UTC, corvus-ch commented on docs/modules/PRODUCT/pages/vss_support_matrix.adoc
> +* *Application HA*: Is access to applications available in high-availability? This means: HS Load-balancer and IP HA
`s/HS/HA/`

2020-05-04 07:48 UTC, corvus-ch commented on docs/modules/PRODUCT/pages/vss_vcsp.adoc
> +TIP: This document is currently in public beta and being worked on actively
Probably also `WARNING`.

2020-05-05 08:15 UTC, closed without merging

2020-05-05 08:15 UTC, tobru commented
Will move to git.vshn.net